version: '3.9'

services:
  webserver:
    image: nginx:latest
    container_name: nginx_docker_report
    restart: unless-stopped
    tty: true
    ports:
      - "8002:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
    networks:
      - report_docker-networks

  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: php_docker_report
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - report_docker-networks
  
  db:
    image: mysql:latest
    container_name: db_docker_report
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: reportcwf
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
    command: --datadir=/var/lib/mysql
    volumes:
      - db:/var/lib/mysql
      - ./mysql/my.conf:/etc/mysql/my.conf
    networks:
      - report_docker-networks
    
networks:
  report_docker-networks:
    driver: bridge

volumes:
  db:
    driver: local